// AUTO-EXPORT: reads Foundry artifacts from out/ and emits typed ABIs into packages/contracts.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";

const OUT = "out";
const TARGET = "../packages/contracts/src/abis.ts";

// Public modules exposed to TS consumers. Each must exist at out/<Name>.sol/<Name>.json.
const EXPOSE = [
  "BasketVault",
  "BasketFactory",
  "ModuleRegistry",
  "NAVEngine",
  "OracleRouter",
  "RebalanceEngine",
  "CreationRedemption",
  "CorporateActionsModule",
  "BufferedTriggerGuard",
  "ProofOfReserve",
  "ChainlinkAdapter",
];

let body = "// AUTO-GENERATED by contracts/scripts/export-abi.mjs — do not edit by hand.\n\n";
for (const name of EXPOSE) {
  const artifact = JSON.parse(readFileSync(join(OUT, `${name}.sol`, `${name}.json`), "utf8"));
  body += `export const ${name}Abi = ${JSON.stringify(artifact.abi)} as const;\n\n`;
}
mkdirSync(dirname(TARGET), { recursive: true });
writeFileSync(TARGET, body);
console.log(`Wrote ${EXPOSE.length} ABIs to ${TARGET}`);
