// AUTO-GENERATED by scripts/sync-contracts.mjs — do not edit by hand.
// Address maps are filled from blockchain/deployments/*.json; empty until deploy.
// Regenerate with `yarn abi:sync`.

export const CHAIN_IDS = {
  robinhoodChainTestnet: 46630,
  arbitrumSepolia: 421614,
} as const;

export type ChainId = (typeof CHAIN_IDS)[keyof typeof CHAIN_IDS];

// role/contract -> address per chain. Empty until deployment.
export const addresses: Record<ChainId, Record<string, `0x${string}`>> = {
  [CHAIN_IDS.robinhoodChainTestnet]: {
    "BasketNavObserver": "0x16221e4fa1842b36587b496f81ad3b51cc78e0b7",
    "BasketVault": "0x94ac71ac16745838748367f0b5b1cade54414277",
    "ChainlinkStreamsSource": "0x9b5747f8a46ebeb70ab4e111dbd873cf7620c2bb",
    "CloneFactory": "0x453b28529273e240120d6475f2369e002deb13f5",
    "CommittedVault": "0x41a7bb85e07c9db6b23ee627bfcef9d6f1fff25b",
    "FairValueNAV": "0xcfaa21689d7273fadbd7576eda0991576900ad96",
    "ForwardCashQueue": "0xf109cf55511d15e7906fbe421a39db9f42121994",
    "KeeperModule": "0x746db09ac8c7de315dcd5a19732033fb0f14f877",
    "ManagedRebalanceVault": "0x2e578bd5e288ae6f62708d1bfd5f806b2f092e61",
    "ManagedVault": "0x41bfa14085ac4439a01b044089d68c0b1ab036b2",
    "MockAPFiller": "0x11b223e71bdb272695f489e5ece2994694cfa512",
    "MockVerifierProxy": "0x7703a06f6e43752b989a4aa6ca5e969d3e5af6cb",
    "PriceAggregator": "0x25f04d55c0b3608c258c21cb603acee197ca5301",
    "RebalanceAuction": "0xd39aa1cab5e24150257e5fed43a4d79c53e47ccc",
    "RebalanceModule": "0x99602fc33c65dfcdbe1b966383ddd9575fdfb60d",
    "RebalanceObserver": "0x47decc7a347cd26804547c07b9817e4c2c5db522",
    "RegistryRebalanceVault": "0x8937a6ee95097b5a794994dce7c90c1168af7205",
    "USDG": "0x5f28d5e0939fdb94943d5c65241cbf850c3d98d1",
    "UniversalSignedSource": "0x41be2284c8bbc5c89b5e2bd4784a10b2646691aa",
    "UniversalSignedSourceWeekend": "0x32207892289a101d8546a430abbdf62dd2049ffd",
  },
  [CHAIN_IDS.arbitrumSepolia]: {},
};
