// AUTO-GENERATED by scripts/sync-contracts.mjs — do not edit by hand.
// Address maps are filled from blockchain/deployments/*.json; empty until deploy.
// Regenerate with `yarn abi:sync`.

export const CHAIN_IDS = {
  robinhoodChainTestnet: 46630,
  arbitrumSepolia: 421614,
} as const;

export type ChainId = (typeof CHAIN_IDS)[keyof typeof CHAIN_IDS];

// role/contract -> address per chain. Empty until deployment.
export const addresses: Record<ChainId, Record<string, `0x${string}`>> = {
  [CHAIN_IDS.robinhoodChainTestnet]: {
    "BasketNavObserver": "0xd63986c4bcb1646cd01d5d0c44037c397292d920",
    "BasketVault": "0x6e2e82baafaf08ac4f2fbc0f7fbb7af596c0539c",
    "ChainlinkStreamsSource": "0xb9dec9b3229c84c63d84bd451766d6e55c8b9d6d",
    "CloneFactory": "0x88d606a5fbcc8ae26676ed34568770049c1991b9",
    "CommittedVault": "0x1f0b54fd73771d5ddd985d57799d6a0ef3b1a7f6",
    "FairValueNAV": "0x3a6f2d311ec60b76ab02892e9af92f7fd9525dac",
    "ForwardCashQueue": "0x2c8b711b3d827283e6687b990a4f877d44ed5ba8",
    "KeeperModule": "0x9845e5ebee7bff6cba532db692c8ca4435a559a8",
    "ManagedRebalanceVault": "0x8128203816ba8782a602c8e12ad95f4d5e0676ec",
    "ManagedVault": "0x557b6e25be3f810ab5ccc922d54e332a02ba13c2",
    "MockAPFiller": "0x11b223e71bdb272695f489e5ece2994694cfa512",
    "MockVerifierProxy": "0xdd31e36d02b3e5dbf47084174cb67a9e3c2cf462",
    "PriceAggregator": "0x9ad520ce8ab6b431aec1eddc4cea99671a6fc567",
    "RebalanceAuction": "0x9601a1c96ff2da6860ab85eec943a1cb911a1502",
    "RebalanceModule": "0x9515441105694d270a5097625980f29d908ea9a6",
    "RebalanceObserver": "0x4cce423e728caed7ac50f5ed5f498775e307a4f8",
    "UniversalSignedSource": "0x76dd5eb19e089779717a2eb23f8424fc72500d2f",
    "UniversalSignedSourceWeekend": "0x8f5df4dfd0cf3f495476280f9616095465b26aba",
  },
  [CHAIN_IDS.arbitrumSepolia]: {},
};
