// AUTO-GENERATED by scripts/sync-demo-tokens.mjs — do not edit by hand.
// Shared demo-token catalog (address/symbol/name) for token search + resolve.

export interface DemoToken {
  address: string;
  symbol: string;
  name: string;
  priceUsd: number;
}

export const demoTokens: DemoToken[] = [
  {
    "address": "0x0c779f3d751a146991e52eb3a7306830f8e7e59e",
    "symbol": "NVDA",
    "name": "NVIDIA Corporation",
    "priceUsd": 208.190002
  },
  {
    "address": "0x0c56701c39946460a563b44a11aa548dce5ad80c",
    "symbol": "GOOGL",
    "name": "Alphabet Inc.",
    "priceUsd": 364.26001
  },
  {
    "address": "0x479ee6cc380f0777fcc8afbec5e2a1f7a16bdcaa",
    "symbol": "GOOG",
    "name": "Alphabet Inc.",
    "priceUsd": 362.290009
  },
  {
    "address": "0x60527a2ef132433e378d89de8be8595c578f4241",
    "symbol": "AAPL",
    "name": "Apple Inc.",
    "priceUsd": 290.549988
  },
  {
    "address": "0xe83429d1051f50d21992825a77abc2ec5e85ceb3",
    "symbol": "MSFT",
    "name": "Microsoft Corporation",
    "priceUsd": 403.410004
  },
  {
    "address": "0x0674a361a6ab8cd11c2bdc2717174692665b7e69",
    "symbol": "AMZN",
    "name": "Amazon.com, Inc.",
    "priceUsd": 244.190002
  },
  {
    "address": "0xcc15db2288bd637f7f259a1d7d2fc274d039c12e",
    "symbol": "AVGO",
    "name": "Broadcom Inc.",
    "priceUsd": 392.160004
  },
  {
    "address": "0x6da4ab90c63cc6f60afde327dffcf683277bbca7",
    "symbol": "META",
    "name": "Meta Platforms, Inc.",
    "priceUsd": 584.590027
  },
  {
    "address": "0xfb34ab8b3b586b2dfbf1ea1b5afe942998e4ae92",
    "symbol": "TSLA",
    "name": "Tesla, Inc.",
    "priceUsd": 396.679993
  },
  {
    "address": "0x41465fb86f3e609b119495333ba66c06458e64e7",
    "symbol": "BRK-A",
    "name": "Berkshire Hathaway Inc.",
    "priceUsd": 729862
  },
  {
    "address": "0xa74da3e26751b979b8520fd0fad24335cb6eeb0d",
    "symbol": "BRK-B",
    "name": "Berkshire Hathaway Inc.",
    "priceUsd": 487.769989
  },
  {
    "address": "0x228109e2c4517c64ea14889c669aa664198671f8",
    "symbol": "LLY",
    "name": "Eli Lilly and Company",
    "priceUsd": 1144.680054
  },
  {
    "address": "0x10cb6bd7fffb5123f5ee0068abb8773af946f20f",
    "symbol": "MU",
    "name": "Micron Technology, Inc.",
    "priceUsd": 935.890015
  },
  {
    "address": "0x025817a0659f384fddfef8124edf1f3696cb0250",
    "symbol": "WMT",
    "name": "Walmart Inc.",
    "priceUsd": 118.879997
  },
  {
    "address": "0xabbbfe02de0aaf17b0b598758d07c57af252234e",
    "symbol": "JPM",
    "name": "JPMorgan Chase & Co.",
    "priceUsd": 312.700012
  },
  {
    "address": "0x51b3f2ce6d4e4f5256d3e7123ddbbe9e5d971dda",
    "symbol": "AMD",
    "name": "Advanced Micro Devices, Inc.",
    "priceUsd": 475.505005
  },
  {
    "address": "0x8c5c463ca48efe819dc51da3347f7697bf7a3f21",
    "symbol": "XOM",
    "name": "Exxon Mobil Corporation",
    "priceUsd": 148.910004
  },
  {
    "address": "0x1059d95bd2d30e1d814da42a0d14d32ea86a3622",
    "symbol": "V",
    "name": "Visa Inc.",
    "priceUsd": 325.049988
  },
  {
    "address": "0x9ecf4b9a156e213e10a5190aab8e87a49c89b9c2",
    "symbol": "ORCL",
    "name": "Oracle Corporation",
    "priceUsd": 205.809998
  },
  {
    "address": "0x5eedd4ee8cb086e20a7539e24cdc493ff5ea08a2",
    "symbol": "JNJ",
    "name": "Johnson & Johnson",
    "priceUsd": 237
  },
  {
    "address": "0xa02ca97a29f9f7f13f5dc1988e746e44918cf62d",
    "symbol": "INTC",
    "name": "Intel Corporation",
    "priceUsd": 107.919998
  },
  {
    "address": "0x24b47bc5ef04fe6f62b5f08b7d6a6f9b23f2548f",
    "symbol": "CSCO",
    "name": "Cisco Systems, Inc.",
    "priceUsd": 120.360001
  },
  {
    "address": "0xce9a8f1cf5436ff8cadb966fa21f929f430463ac",
    "symbol": "COST",
    "name": "Costco Wholesale Corporation",
    "priceUsd": 968.590027
  },
  {
    "address": "0x1f2aadd743515ff132b7953ac8afcda36979fa6f",
    "symbol": "MA",
    "name": "Mastercard Incorporated",
    "priceUsd": 495.23999
  },
  {
    "address": "0xbafb956f66836946acba755a4a6e5e8fe08343de",
    "symbol": "LRCX",
    "name": "Lam Research Corporation",
    "priceUsd": 327.160004
  },
  {
    "address": "0x8208030b981310bbc8945df8ef0229f45b68cfe6",
    "symbol": "ABBV",
    "name": "AbbVie Inc.",
    "priceUsd": 225.419998
  },
  {
    "address": "0xc8e27e23abcd9c70346269d2c0e16cbbaaf430e7",
    "symbol": "AMAT",
    "name": "Applied Materials, Inc.",
    "priceUsd": 499.209991
  },
  {
    "address": "0x9f83cca19f1ec80acacb3636bab0ef6f77a78c8d",
    "symbol": "BAC",
    "name": "Bank of America Corporation",
    "priceUsd": 54.419998
  },
  {
    "address": "0xc7b650b8766829e4e80fc0266d1b240d89979e83",
    "symbol": "CVX",
    "name": "Chevron Corporation",
    "priceUsd": 186.759995
  },
  {
    "address": "0x2bc4eb2547aaafd63d80c90af9af4ea7e1b869fe",
    "symbol": "UNH",
    "name": "UnitedHealth Group Incorporated",
    "priceUsd": 413
  },
  {
    "address": "0x3f2f027b1519a10550e1ae21779ac19ee4cb2ebd",
    "symbol": "KO",
    "name": "The Coca-Cola Company",
    "priceUsd": 81.339996
  },
  {
    "address": "0x389a0f6ff11d5c8a716db18dc982f29316d6e4fe",
    "symbol": "PG",
    "name": "The Procter & Gamble Company",
    "priceUsd": 148.669998
  },
  {
    "address": "0x0f6ad601dbfed0bf0fba86ca4ee486a90e2ffbd8",
    "symbol": "NFLX",
    "name": "Netflix, Inc.",
    "priceUsd": 81.410004
  },
  {
    "address": "0xf9a897e8e7f0dcf0b09755e314aec8341789e74b",
    "symbol": "GE",
    "name": "GE Aerospace",
    "priceUsd": 330.440002
  },
  {
    "address": "0x99c2f1e831460f93fb1fb1169c29fd35a27ef710",
    "symbol": "MS",
    "name": "Morgan Stanley",
    "priceUsd": 210.25
  },
  {
    "address": "0x391463a14533c69eeef15f4ae459eed649b04c31",
    "symbol": "HD",
    "name": "The Home Depot, Inc.",
    "priceUsd": 321.329987
  },
  {
    "address": "0xac7cc46154b0a35cb8a9ee6dfd4bb8832b91c625",
    "symbol": "PLTR",
    "name": "Palantir Technologies Inc.",
    "priceUsd": 132.070007
  },
  {
    "address": "0x658c56d58135be94f5d67292cfb3ec7a96aa1b8e",
    "symbol": "GS",
    "name": "The Goldman Sachs Group, Inc.",
    "priceUsd": 1032.01001
  },
  {
    "address": "0xd30419033ffc9f08c6f1058e7c77add564fc3151",
    "symbol": "MRK",
    "name": "Merck & Co., Inc.",
    "priceUsd": 119.599998
  },
  {
    "address": "0xc81a2e9b73323ba512e8db9db3bb9d1684836d21",
    "symbol": "PM",
    "name": "Philip Morris International Inc.",
    "priceUsd": 178.490005
  },
  {
    "address": "0x8cc63a6baa2e92081604655a46303c3fcf63a7b5",
    "symbol": "KLAC",
    "name": "KLA Corporation",
    "priceUsd": 2139.370117
  },
  {
    "address": "0x4164706af1b83b51378d0aecbeca22dcc07c6f14",
    "symbol": "RY",
    "name": "Royal Bank of Canada",
    "priceUsd": 197.889999
  },
  {
    "address": "0x14ad33863e26ffc9ba559ae68f6de5a0395deee6",
    "symbol": "TXN",
    "name": "Texas Instruments Incorporated",
    "priceUsd": 288.630005
  },
  {
    "address": "0x8c06e70fa6b4bb109972fd896bce418c546ca6aa",
    "symbol": "IBM",
    "name": "International Business Machines Corporation",
    "priceUsd": 277.48999
  },
  {
    "address": "0xb0089b52505417f0febdd96c618c9206b27d06b6",
    "symbol": "WFC",
    "name": "Wells Fargo & Company",
    "priceUsd": 82
  },
  {
    "address": "0x850bc38d0dace6aeb9da7327ce01a0df23b00ef5",
    "symbol": "SNDK",
    "name": "Sandisk Corporation",
    "priceUsd": 1646.540039
  },
  {
    "address": "0x1ae31eb93b02c93806334fbc5ab6d2baac3b74da",
    "symbol": "DELL",
    "name": "Dell Technologies Inc.",
    "priceUsd": 381.779999
  },
  {
    "address": "0xd2c3cfc85c08572136103f90d59772dfd364221a",
    "symbol": "RTX",
    "name": "RTX Corporation",
    "priceUsd": 181.559998
  },
  {
    "address": "0xd6476dc760fe9e9eee3010596ceec3885f8c9956",
    "symbol": "LIN",
    "name": "Linde plc",
    "priceUsd": 515.590027
  },
  {
    "address": "0x9c50061f0fb277272135b68c7d0e3d13abb20281",
    "symbol": "GEV",
    "name": "GE Vernova Inc.",
    "priceUsd": 920.150024
  },
  {
    "address": "0x318d80bd8ff798937ec2c949c8dc8b37404a9037",
    "symbol": "C",
    "name": "Citigroup Inc.",
    "priceUsd": 134.729996
  },
  {
    "address": "0x865d1c01fc1dd56a67923ef32db8aa109eb7fb85",
    "symbol": "MRVL",
    "name": "Marvell Technology, Inc.",
    "priceUsd": 266.880005
  },
  {
    "address": "0xa6b8294b65de6b79eda3fcd96d255954f0c1e5b3",
    "symbol": "PANW",
    "name": "Palo Alto Networks, Inc.",
    "priceUsd": 260.519989
  },
  {
    "address": "0x120ac58a50ef9b59fe0fef2de991357e01760121",
    "symbol": "AXP",
    "name": "American Express Company",
    "priceUsd": 318.380005
  },
  {
    "address": "0x11db093924ca6617669d23c94c2ce39bc84db7b5",
    "symbol": "QCOM",
    "name": "QUALCOMM Incorporated",
    "priceUsd": 205.419998
  },
  {
    "address": "0xe14ac0ce8e6449dbdd7ce5be0e3f3dced6d7e809",
    "symbol": "TMUS",
    "name": "T-Mobile US, Inc.",
    "priceUsd": 179.460007
  },
  {
    "address": "0x514e346bea9c069fa5f551fb2d5a0b4ac2e2ce2d",
    "symbol": "MCD",
    "name": "McDonald's Corporation",
    "priceUsd": 282.25
  },
  {
    "address": "0x07b558b9f42a1853701125068c50247d9bbedca7",
    "symbol": "PEP",
    "name": "PepsiCo, Inc.",
    "priceUsd": 142.779999
  },
  {
    "address": "0x09765fe510515d2f674c9c02871d1e294fe6abe3",
    "symbol": "VZ",
    "name": "Verizon Communications Inc.",
    "priceUsd": 45.779999
  },
  {
    "address": "0x8a20ea4e2985d1d300ce058dbff1379c4d29f96d",
    "symbol": "ANET",
    "name": "Arista Networks, Inc.",
    "priceUsd": 152.160004
  },
  {
    "address": "0x5a4d1ceb1694651615433fd6b5cbb211e8fa6823",
    "symbol": "TD",
    "name": "The Toronto-Dominion Bank",
    "priceUsd": 114.639999
  },
  {
    "address": "0xc9820c9c834c28f6cfd15aeacd6174ff01f08388",
    "symbol": "TJX",
    "name": "The TJX Companies, Inc.",
    "priceUsd": 164.869995
  },
  {
    "address": "0x0984b0e0ac01454593cff3e127a8cdf11fcced90",
    "symbol": "APH",
    "name": "Amphenol Corporation",
    "priceUsd": 154.070007
  },
  {
    "address": "0x2e1c585b4091dd593a682bc07ab9df6b0125e892",
    "symbol": "AMGN",
    "name": "Amgen Inc.",
    "priceUsd": 344.565002
  },
  {
    "address": "0xf98dd26068c617833ac01b8b20678971b0ac38b7",
    "symbol": "TMO",
    "name": "Thermo Fisher Scientific Inc.",
    "priceUsd": 494.070007
  },
  {
    "address": "0xb7f32eabac96b3e3b20ba355f0697f74c1dd9f06",
    "symbol": "NEE",
    "name": "NextEra Energy, Inc.",
    "priceUsd": 84.830002
  },
  {
    "address": "0x1d922ff2012d6927eab33d79889bcf91af0613d1",
    "symbol": "DIS",
    "name": "The Walt Disney Company",
    "priceUsd": 99.330002
  },
  {
    "address": "0xeee2742b68522402b1740837c9e6deb88ea0ec17",
    "symbol": "WDC",
    "name": "Western Digital Corporation",
    "priceUsd": 517.719971
  },
  {
    "address": "0x74e6fcaeab8b5b0e2388d2bdb639ed7032062964",
    "symbol": "APP",
    "name": "AppLovin Corporation",
    "priceUsd": 520.840027
  },
  {
    "address": "0x094afb9339ad307acfa4a15eb960aa5c6252d675",
    "symbol": "CRWD",
    "name": "CrowdStrike Holdings, Inc.",
    "priceUsd": 644.929993
  },
  {
    "address": "0x65ddc03b94f18fa7b7b22349d463ad12bb7bba7d",
    "symbol": "BA",
    "name": "The Boeing Company",
    "priceUsd": 214.509995
  },
  {
    "address": "0xe2bbde9891696816341e2a7dcad2bae254caf596",
    "symbol": "BLK",
    "name": "BlackRock, Inc.",
    "priceUsd": 1011.960022
  },
  {
    "address": "0x51ea10f64493fd1c6b9271f2f0add1905b967d42",
    "symbol": "T",
    "name": "AT&T Inc.",
    "priceUsd": 22.709999
  },
  {
    "address": "0xbfabfa79bafc206e51c929ebe45aa47037653722",
    "symbol": "UNP",
    "name": "Union Pacific Corporation",
    "priceUsd": 271.279999
  },
  {
    "address": "0x1a59764e2408801db9058126806b621e9779cb71",
    "symbol": "SCHW",
    "name": "The Charles Schwab Corporation",
    "priceUsd": 88.769997
  },
  {
    "address": "0xde8928416bb5cbd9da30a2190ca17c63ab779cb1",
    "symbol": "GILD",
    "name": "Gilead Sciences, Inc.",
    "priceUsd": 125.5
  },
  {
    "address": "0x9ceaa4636b8311011ce4ac8161267a7ca60c8146",
    "symbol": "COP",
    "name": "ConocoPhillips",
    "priceUsd": 116.790001
  },
  {
    "address": "0x80b545cade501217ed4dd6d89ad8c2c48c757a6b",
    "symbol": "ISRG",
    "name": "Intuitive Surgical, Inc.",
    "priceUsd": 426.609985
  },
  {
    "address": "0x9b00c0ab184a80a8b3246ce68ca88565f5b4c9e5",
    "symbol": "PFE",
    "name": "Pfizer Inc.",
    "priceUsd": 25.700001
  },
  {
    "address": "0xeb18aa32e99ec50946b927302d9fae1ed447e357",
    "symbol": "ETN",
    "name": "Eaton Corporation plc",
    "priceUsd": 401.720001
  },
  {
    "address": "0xe2be9014284bb8f4ca674aca708b888eec8c6429",
    "symbol": "IBKR",
    "name": "Interactive Brokers Group, Inc.",
    "priceUsd": 86.330002
  },
  {
    "address": "0x26583f1114903c9843d3d59e1024b54965316d86",
    "symbol": "BX",
    "name": "Blackstone Inc.",
    "priceUsd": 120.290001
  },
  {
    "address": "0x475a6fbfc03c9e642e31b570c0e7e1e37ff183ad",
    "symbol": "GLW",
    "name": "Corning Incorporated",
    "priceUsd": 173.940002
  },
  {
    "address": "0x737e221af45b1363604e2b5000c49da7295db62f",
    "symbol": "SHOP",
    "name": "Shopify Inc.",
    "priceUsd": 110.419998
  },
  {
    "address": "0x68b617f9f43ed055dd49a42d5f2c78f069f39e1f",
    "symbol": "CRM",
    "name": "Salesforce, Inc.",
    "priceUsd": 175.350006
  },
  {
    "address": "0x874d0b933fe3432637d91d9e546ef8dbc679d2fd",
    "symbol": "SCCO",
    "name": "Southern Copper Corporation",
    "priceUsd": 175.169998
  },
  {
    "address": "0x5ac74cd6cc7a4a61798261f3391f1761be109974",
    "symbol": "UBER",
    "name": "Uber Technologies, Inc.",
    "priceUsd": 70.379997
  },
  {
    "address": "0x7164844ea2bdf330d5943c002160deede78a3bcf",
    "symbol": "HON",
    "name": "Honeywell International Inc.",
    "priceUsd": 215.699997
  },
  {
    "address": "0x40cec2fa0d2be061e3f8c0aba4ef715440401db6",
    "symbol": "DHR",
    "name": "Danaher Corporation",
    "priceUsd": 188.410004
  },
  {
    "address": "0x305c15f5d9f47fb37cb4ac80354e9ff8b144026b",
    "symbol": "CB",
    "name": "Chubb Limited",
    "priceUsd": 325.130005
  },
  {
    "address": "0x4d3d1596ad153de32219b21abd32e35f054786ec",
    "symbol": "SPGI",
    "name": "S&P Global Inc.",
    "priceUsd": 424.820007
  },
  {
    "address": "0x883533e4a63d95d44c5c94482b0906f2cb9d637f",
    "symbol": "CVS",
    "name": "CVS Health Corporation",
    "priceUsd": 97.059998
  },
  {
    "address": "0xf749ea9e718ca56d95fb0bba8851ed849fddde57",
    "symbol": "BKNG",
    "name": "Booking Holdings Inc.",
    "priceUsd": 163.990005
  },
  {
    "address": "0x2c5875c03a91fca3df405b29fab7cba401e283cd",
    "symbol": "ENB",
    "name": "Enbridge Inc.",
    "priceUsd": 55.540001
  },
  {
    "address": "0x5a333af94fb7085dc94f1cda43c35c6df421e6e2",
    "symbol": "MO",
    "name": "Altria Group, Inc.",
    "priceUsd": 71.559998
  },
  {
    "address": "0x0bc9d08f5e5863ae94a8c061a81b1dab2b9c0885",
    "symbol": "LOW",
    "name": "Lowe's Companies, Inc.",
    "priceUsd": 217.369995
  },
  {
    "address": "0xd435ada8f2e61fef6ba6b2b8e602df28869bdf96",
    "symbol": "LMT",
    "name": "Lockheed Martin Corporation",
    "priceUsd": 530.130005
  },
  {
    "address": "0xea84f2cf90f3006e96c97c73af7d288e3df05b6c",
    "symbol": "PGR",
    "name": "The Progressive Corporation",
    "priceUsd": 200.130005
  },
  {
    "address": "0x399b2f708a17c2230df6665917803940a2460893",
    "symbol": "SYK",
    "name": "Stryker Corporation",
    "priceUsd": 314.01001
  },
  {
    "address": "0x1c521c260ad075202c7a1c0398d21c11ccf407af",
    "symbol": "BMY",
    "name": "Bristol-Myers Squibb Company",
    "priceUsd": 56.48
  },
  {
    "address": "0x5a685b3877e82a88b5274f22102ba75f08383ee2",
    "symbol": "SBUX",
    "name": "Starbucks Corporation",
    "priceUsd": 97.410004
  },
  {
    "address": "0x3829dc04d6b10a70922c5b4542cb54182c0c3b8c",
    "symbol": "VRTX",
    "name": "Vertex Pharmaceuticals Incorporated",
    "priceUsd": 445.769989
  },
  {
    "address": "0xafe8f4b4dbcf238d3fc6de4807848dd311abd57a",
    "symbol": "COF",
    "name": "Capital One Financial Corporation",
    "priceUsd": 183.350006
  },
  {
    "address": "0x3ca1794f9b6eb0371df0552a448e374b6e6b9e76",
    "symbol": "PH",
    "name": "Parker-Hannifin Corporation",
    "priceUsd": 905.530029
  },
  {
    "address": "0xfafb598a02a124f29fb56c6ef5909461caf15767",
    "symbol": "NOW",
    "name": "ServiceNow, Inc.",
    "priceUsd": 106.970001
  },
  {
    "address": "0x9e5c7535635e55d343dc1f8db906d0296cf1d875",
    "symbol": "VRT",
    "name": "Vertiv Holdings Co",
    "priceUsd": 289.519989
  },
  {
    "address": "0x5cf758959e84c9d84f4dde19671153ac16ebd5ea",
    "symbol": "CDNS",
    "name": "Cadence Design Systems, Inc.",
    "priceUsd": 390.899994
  },
  {
    "address": "0x3b601e35afb3549f8fb9de8aa2aff7dc3cb4bf2d",
    "symbol": "SO",
    "name": "The Southern Company",
    "priceUsd": 92.949997
  },
  {
    "address": "0xf3fbfa968645e6702ef3c373ed38df2ac39c8792",
    "symbol": "ACN",
    "name": "Accenture plc",
    "priceUsd": 173.470001
  },
  {
    "address": "0x64c86a2bf5dcfbdd04406d6df8b08d1c9e5a3d07",
    "symbol": "SPOT",
    "name": "Spotify Technology S.A.",
    "priceUsd": 496.220001
  },
  {
    "address": "0xf5a37e6c0d6d3fc7b3516a24af8e822c2dc87cf5",
    "symbol": "MAR",
    "name": "Marriott International, Inc.",
    "priceUsd": 393.609985
  },
  {
    "address": "0x5f8a74e816867ed6c4c6cc4de20051b831310b87",
    "symbol": "FTNT",
    "name": "Fortinet, Inc.",
    "priceUsd": 138.389999
  },
  {
    "address": "0xf9beb5c654c9fa35dae631b16f235d5bdd62abba",
    "symbol": "BNS",
    "name": "The Bank of Nova Scotia",
    "priceUsd": 81.699997
  },
  {
    "address": "0x6bd60f54ff76bb94829e8fe2d71153c20dfaf817",
    "symbol": "HWM",
    "name": "Howmet Aerospace Inc.",
    "priceUsd": 257.160004
  },
  {
    "address": "0x93bac65d3e1bef99c051a4863c09e396580b33ea",
    "symbol": "BN",
    "name": "Brookfield Corporation",
    "priceUsd": 45.509998
  },
  {
    "address": "0x1fd1815e71118c018b617d3f1bc55060a08b32b8",
    "symbol": "NEM",
    "name": "Newmont Corporation",
    "priceUsd": 98.540001
  },
  {
    "address": "0x3674307c17a9a44a3de2268346fb014b4b35fe04",
    "symbol": "PWR",
    "name": "Quanta Services, Inc.",
    "priceUsd": 691.950012
  },
  {
    "address": "0x1fc208f80de6011aa14f8cb1c45f8bc54aaab1f7",
    "symbol": "DUK",
    "name": "Duke Energy Corporation",
    "priceUsd": 123.82
  },
  {
    "address": "0x162eee48d4a1cc0f9cc51a36175475b47e59b20c",
    "symbol": "BNY",
    "name": "The Bank of New York Mellon Cor",
    "priceUsd": 143.25
  },
  {
    "address": "0xc2c905182c7f182be7125e1e1323abee180f8f0f",
    "symbol": "CME",
    "name": "CME Group Inc.",
    "priceUsd": 255.940002
  },
  {
    "address": "0x52e262471477436b252029a08d590ae51f45029a",
    "symbol": "MCK",
    "name": "McKesson Corporation",
    "priceUsd": 784.22998
  },
  {
    "address": "0x05981fc3f9cfc42de1970d0c80e4eff1c4a1cca0",
    "symbol": "CNQ",
    "name": "Canadian Natural Resources Limited",
    "priceUsd": 44.810001
  },
  {
    "address": "0xae18c273d4a24869bc43ea0cff24df23d43d4ae4",
    "symbol": "ADBE",
    "name": "Adobe Inc.",
    "priceUsd": 237.880005
  },
  {
    "address": "0xc4474d8c819da8d0abe455d697c66bd8579ed861",
    "symbol": "PNC",
    "name": "The PNC Financial Services Group, Inc.",
    "priceUsd": 232.179993
  },
  {
    "address": "0x1454a0c8006bcb7281e4e1ea8c837614adf634fc",
    "symbol": "GD",
    "name": "General Dynamics Corporation",
    "priceUsd": 345.679993
  },
  {
    "address": "0x435347fac6e897f685b5da83b20426436a63394c",
    "symbol": "WM",
    "name": "Waste Management, Inc.",
    "priceUsd": 221.300003
  },
  {
    "address": "0xda0859173a4fb65b9121790dae2c31a181e0c1e2",
    "symbol": "FCX",
    "name": "Freeport-McMoRan Inc.",
    "priceUsd": 64.25
  },
  {
    "address": "0x3552f1fd63603fac2eb287334d4c5b07a9fe59c8",
    "symbol": "MNST",
    "name": "Monster Beverage Corporation",
    "priceUsd": 90.150002
  },
  {
    "address": "0xefbae0f009a10f830ab5cb9afa221bb6f7acb550",
    "symbol": "KKR",
    "name": "KKR & Co. Inc.",
    "priceUsd": 95.839996
  },
  {
    "address": "0xf787a85fc7d721d3336b88f3aadb3de2609291ae",
    "symbol": "USB",
    "name": "U.S. Bancorp",
    "priceUsd": 56.02
  },
  {
    "address": "0x30b8d3232477f9237c079bd411d9bbd243d70851",
    "symbol": "WMB",
    "name": "The Williams Companies, Inc.",
    "priceUsd": 71.589996
  },
  {
    "address": "0x034b2880f86d8625182669582d621f38a38d5216",
    "symbol": "SNPS",
    "name": "Synopsys, Inc.",
    "priceUsd": 465.269989
  },
  {
    "address": "0x675951b0988b85c222d466cf0e84d811148638b4",
    "symbol": "ELV",
    "name": "Elevance Health, Inc.",
    "priceUsd": 424.429993
  },
  {
    "address": "0x0897e0e1e5e95a88e58109f396afd2df1883adba",
    "symbol": "UPS",
    "name": "United Parcel Service, Inc.",
    "priceUsd": 107.870003
  },
  {
    "address": "0x8a27880c466bb86cebb7a1c23d98586721707e11",
    "symbol": "CMI",
    "name": "Cummins Inc.",
    "priceUsd": 669.22998
  },
  {
    "address": "0x3dd2f1679c3b612237c02011bf3d1e374cd65ed6",
    "symbol": "CEG",
    "name": "Constellation Energy Corporation",
    "priceUsd": 251.649994
  },
  {
    "address": "0xa808f43773b1453361e96857c3a89c37ee6b3cb6",
    "symbol": "CSX",
    "name": "CSX Corporation",
    "priceUsd": 47.279999
  },
  {
    "address": "0x489c64433fcac39e8894e1142ee251cb32898bd7",
    "symbol": "CMCSA",
    "name": "Comcast Corporation",
    "priceUsd": 23.85
  },
  {
    "address": "0x26c0404a077fa18ff1dda056d059bcd68c20cf76",
    "symbol": "JCI",
    "name": "Johnson Controls International plc",
    "priceUsd": 147.75
  },
  {
    "address": "0x185d60b29c37c03e49732c373b9de8b7e25c0f16",
    "symbol": "SNOW",
    "name": "Snowflake Inc.",
    "priceUsd": 239.660004
  },
  {
    "address": "0xc8058b33243f56a29019bf71db3d691df2145a85",
    "symbol": "SLB",
    "name": "SLB N.V.",
    "priceUsd": 55.849998
  },
  {
    "address": "0x94d484ead17e9da5d42948fb25ef8a2df28fe8fc",
    "symbol": "HCA",
    "name": "HCA Healthcare, Inc.",
    "priceUsd": 374.899994
  },
  {
    "address": "0xb05f7763d6c8e12d722d24bdfd455633e8c865d9",
    "symbol": "MDLZ",
    "name": "Mondelez International, Inc.",
    "priceUsd": 62.93
  },
  {
    "address": "0xa3e6857552d038697236d990a79e5b22a431ea24",
    "symbol": "MMM",
    "name": "3M Company",
    "priceUsd": 156.389999
  },
  {
    "address": "0xe45f55c870aeab8f0c6a7fef5a84bc51412fda6d",
    "symbol": "DDOG",
    "name": "Datadog, Inc.",
    "priceUsd": 227.339996
  },
  {
    "address": "0x1e5af3072ab0bec30daf9a3245d480c4f952cb08",
    "symbol": "MRSH",
    "name": "Marsh & McLennan Companies, Inc.",
    "priceUsd": 165.520004
  },
  {
    "address": "0x18d400467560e7f67b273c20b29e7fd69c216887",
    "symbol": "MELI",
    "name": "MercadoLibre, Inc.",
    "priceUsd": 1641.160034
  },
  {
    "address": "0xeaf341a351393d76b1e9c9f1fd461b21be25c141",
    "symbol": "CI",
    "name": "The Cigna Group",
    "priceUsd": 295
  },
  {
    "address": "0x7ae8edfc2278a07bf58f97736a8e40f95c2a8072",
    "symbol": "HOOD",
    "name": "Robinhood Markets, Inc.",
    "priceUsd": 83.769997
  },
  {
    "address": "0xe6cefeb13fc39eaa6f636ee2cf179163845f389c",
    "symbol": "INTU",
    "name": "Intuit Inc.",
    "priceUsd": 293.779999
  },
  {
    "address": "0x8e11a90778cdcbb82d109d6d5dcfcbe183a99a9a",
    "symbol": "NET",
    "name": "Cloudflare, Inc.",
    "priceUsd": 236.130005
  },
  {
    "address": "0x445cddb7907ba17d211e679e102b05344ebb407f",
    "symbol": "NOC",
    "name": "Northrop Grumman Corporation",
    "priceUsd": 548.669983
  },
  {
    "address": "0x51d870bd4ae9a5c09efc4a46ef943d9909545f94",
    "symbol": "HLT",
    "name": "Hilton Worldwide Holdings Inc.",
    "priceUsd": 342.570007
  },
  {
    "address": "0xdd3578a7fe469758fdedbb1c13650a524bc1c4a5",
    "symbol": "MPC",
    "name": "Marathon Petroleum Corporation",
    "priceUsd": 258.149994
  },
  {
    "address": "0x94732767e07f8d775c77f818acc3b736cca94311",
    "symbol": "EMR",
    "name": "Emerson Electric Co.",
    "priceUsd": 142.419998
  },
  {
    "address": "0x4100e1e584d33314a90cf8599ed2b5ff837a26a3",
    "symbol": "ABNB",
    "name": "Airbnb, Inc.",
    "priceUsd": 131.350006
  },
  {
    "address": "0x7f4993223f1868c14af146ce48a2c0fbab9bc2fb",
    "symbol": "VLO",
    "name": "Valero Energy Corporation",
    "priceUsd": 253.779999
  },
  {
    "address": "0x11dbe08d9e7dd814b1841950891211eba1a18e21",
    "symbol": "AEM",
    "name": "Agnico Eagle Mines Limited",
    "priceUsd": 159.929993
  },
  {
    "address": "0xf866334730ceddc33a53ace9ab1593f900fd35c8",
    "symbol": "FDX",
    "name": "FedEx Corporation",
    "priceUsd": 331.76001
  },
  {
    "address": "0xc00669896d76d997ed51bbdaa0baba23941f529d",
    "symbol": "APO",
    "name": "Apollo Global Management, Inc.",
    "priceUsd": 132.699997
  },
  {
    "address": "0x0e323a8672f6197fc21557508e2a3d19848211c5",
    "symbol": "ORLY",
    "name": "O'Reilly Automotive, Inc.",
    "priceUsd": 89.489998
  },
  {
    "address": "0x0caf8bc113fb85b17d38a396fa6381413f3202a2",
    "symbol": "SHW",
    "name": "The Sherwin-Williams Company",
    "priceUsd": 310.549988
  },
  {
    "address": "0x95350b0fd5d42dc1bd5f202b85bb8d505e81a35e",
    "symbol": "EOG",
    "name": "EOG Resources, Inc.",
    "priceUsd": 137.330002
  },
  {
    "address": "0x60b390bfc7239ce9954d433fc437b4578a4c15ff",
    "symbol": "ROST",
    "name": "Ross Stores, Inc.",
    "priceUsd": 229.449997
  },
  {
    "address": "0xc016bc03fb5d209b4dfd43f4ff42bc508c9f38fa",
    "symbol": "CVNA",
    "name": "Carvana Co.",
    "priceUsd": 69.610001
  },
  {
    "address": "0x3ca8ab8d0cf612440aa001d09a82e8dbc53bfdea",
    "symbol": "SU",
    "name": "Suncor Energy Inc.",
    "priceUsd": 61.200001
  },
  {
    "address": "0x542a9cb0dc88871fd7f838b49248af313e43b050",
    "symbol": "PSX",
    "name": "Phillips 66",
    "priceUsd": 179
  },
  {
    "address": "0x9a9cb44c2326cf75af77af409d1cf8e0c45141f9",
    "symbol": "MPWR",
    "name": "Monolithic Power Systems, Inc.",
    "priceUsd": 1531.97998
  },
  {
    "address": "0xf28c0158152b77510f5bb013c738c85c42835a32",
    "symbol": "ECL",
    "name": "Ecolab Inc.",
    "priceUsd": 264.440002
  },
  {
    "address": "0x2ce7b357fc915c84585ceec9a3e0f6b58edbc3f9",
    "symbol": "CTAS",
    "name": "Cintas Corporation",
    "priceUsd": 179.869995
  },
  {
    "address": "0x3a52c9fac6099a5bbadcdbe6310bf8aa27d314b0",
    "symbol": "NXPI",
    "name": "NXP Semiconductors N.V.",
    "priceUsd": 297.410004
  },
  {
    "address": "0x98caf0d255b8c68d0036f1c18627f5973f4cc747",
    "symbol": "RCL",
    "name": "Royal Caribbean Cruises Ltd.",
    "priceUsd": 282.26001
  },
  {
    "address": "0x3ed39dca6656e92badeace07d0f6c5b17a43df1e",
    "symbol": "CL",
    "name": "Colgate-Palmolive Company",
    "priceUsd": 87.800003
  },
  {
    "address": "0x7d420f01048e1be852b5883af55cdeafae1d91f9",
    "symbol": "ITW",
    "name": "Illinois Tool Works Inc.",
    "priceUsd": 256.549988
  },
  {
    "address": "0x96e47b47f9b2d22fb0d60fce90eb406cbc1b8d01",
    "symbol": "BSX",
    "name": "Boston Scientific Corporation",
    "priceUsd": 48.959999
  },
  {
    "address": "0x63668f424bb3046fb63779e07d70aa28293dfbda",
    "symbol": "AON",
    "name": "Aon plc",
    "priceUsd": 331.589996
  },
  {
    "address": "0xa506d552dd0f24f6bad7d900fa0947eddf641051",
    "symbol": "GM",
    "name": "General Motors Company",
    "priceUsd": 83.760002
  },
  {
    "address": "0x7644523284e7a2f693f826948960ea6294f60677",
    "symbol": "KMI",
    "name": "Kinder Morgan, Inc.",
    "priceUsd": 31.34
  },
  {
    "address": "0xb8ab822a4fc18ffb33854417ccb479b7e0830dde",
    "symbol": "AEP",
    "name": "American Electric Power Company, Inc.",
    "priceUsd": 127.760002
  },
  {
    "address": "0xb72d5abb9c8eddd1f580a501b874efca5b3d9c3a",
    "symbol": "COHR",
    "name": "Coherent Corp.",
    "priceUsd": 355.940002
  },
  {
    "address": "0x0e4489418b44c7767fbbe981e66e4668d985c983",
    "symbol": "NSC",
    "name": "Norfolk Southern Corporation",
    "priceUsd": 312.320007
  },
  {
    "address": "0x5ce27df5e04d2c1eb47e05474a79f8b4619ae05d",
    "symbol": "MSI",
    "name": "Motorola Solutions, Inc.",
    "priceUsd": 414.070007
  },
  {
    "address": "0x520b997ece1a584fdfd37db1bf111ce84b2f285c",
    "symbol": "TDG",
    "name": "TransDigm Group Incorporated",
    "priceUsd": 1257.23999
  },
  {
    "address": "0xc68ae3614261e2332a52498e2ae2c2f23629f161",
    "symbol": "CRH",
    "name": "CRH plc",
    "priceUsd": 103.699997
  },
  {
    "address": "0x08f7807a984bdd4ee9f80451ecd18f2790d79142",
    "symbol": "BE",
    "name": "Bloom Energy Corporation",
    "priceUsd": 259.609985
  },
  {
    "address": "0x574c9baa19332fdb557e0888952c6ef271d2267b",
    "symbol": "LITE",
    "name": "Lumentum Holdings Inc.",
    "priceUsd": 821.76001
  },
  {
    "address": "0xb7403286b20617ba8af5dc586e85d67763358ea7",
    "symbol": "URI",
    "name": "United Rentals, Inc.",
    "priceUsd": 1094.170044
  },
  {
    "address": "0xd0c6422d9e094f8baf3cee2b35e736fb730889f3",
    "symbol": "DASH",
    "name": "DoorDash, Inc.",
    "priceUsd": 155.669998
  },
  {
    "address": "0x2fa2d32b015464c3631d86160f15ec3da3359d6c",
    "symbol": "WBD",
    "name": "Warner Bros. Discovery, Inc.",
    "priceUsd": 26.559999
  },
  {
    "address": "0xded5edac5db2acd416a2f475899db3e66d8a86b1",
    "symbol": "RKLB",
    "name": "Rocket Lab Corporation",
    "priceUsd": 108.230003
  },
  {
    "address": "0x443abfc70d403dad3518dcd98e10bc110a6f2297",
    "symbol": "RSG",
    "name": "Republic Services, Inc.",
    "priceUsd": 210.179993
  },
  {
    "address": "0x3270f62d0067fc07bc999cfb1a2ffba43375a521",
    "symbol": "NKE",
    "name": "NIKE, Inc.",
    "priceUsd": 44.650002
  },
  {
    "address": "0xe88b7bd696bee0dda48046f52ca1678520ce58d8",
    "symbol": "TRV",
    "name": "The Travelers Companies, Inc.",
    "priceUsd": 300.25
  },
  {
    "address": "0x086a8e15e124bd3dc12ca98fc04a422930ff4a32",
    "symbol": "REGN",
    "name": "Regeneron Pharmaceuticals, Inc.",
    "priceUsd": 616.179993
  },
  {
    "address": "0xfa95460d1e43eee1a2e37480eced48b73fabd693",
    "symbol": "BKR",
    "name": "Baker Hughes Company",
    "priceUsd": 63.549999
  },
  {
    "address": "0x77ce124eaea6325af71af70216440c9ae384a704",
    "symbol": "B",
    "name": "Barrick Mining Corporation",
    "priceUsd": 39.150002
  },
  {
    "address": "0x11c2e580aa324c045d3ad204fbb5a5065677ef28",
    "symbol": "GWW",
    "name": "W.W. Grainger, Inc.",
    "priceUsd": 1329.800049
  },
  {
    "address": "0x8996e09715d290cc68bade0c923d22593ba8af26",
    "symbol": "TFC",
    "name": "Truist Financial Corporation",
    "priceUsd": 49.43
  },
  {
    "address": "0x984921c2c4beb28ced53942ac5a84e2bd97fc9e9",
    "symbol": "APD",
    "name": "Air Products and Chemicals, Inc.",
    "priceUsd": 282.980011
  },
  {
    "address": "0x23925004e13ea6689a028d645e18c7b73cdf0dbb",
    "symbol": "FIX",
    "name": "Comfort Systems USA, Inc.",
    "priceUsd": 1831.560059
  },
  {
    "address": "0x50476f269ad95c3c4489bdfe3d56224fc1112d50",
    "symbol": "HPE",
    "name": "Hewlett Packard Enterprise Company",
    "priceUsd": 48.27
  },
  {
    "address": "0xe411cf1670b1331c3dd9399f44768612eaaa08d9",
    "symbol": "PCAR",
    "name": "PACCAR Inc",
    "priceUsd": 119.690002
  },
  {
    "address": "0xf0f432501b182505a09f7f5a5fa1efbf2d6f9869",
    "symbol": "AFL",
    "name": "Aflac Incorporated",
    "priceUsd": 115.610001
  },
  {
    "address": "0x8e3536597df9e44ff23fa47aa2eca51237d1e827",
    "symbol": "SRE",
    "name": "Sempra",
    "priceUsd": 90.870003
  },
  {
    "address": "0x409f5ab06a463f3a6542720ad361a8167cf1e2ce",
    "symbol": "DB",
    "name": "Deutsche Bank Aktiengesellschaft",
    "priceUsd": 31.9
  },
  {
    "address": "0xbbe9c91fa759ae09fcb684856b609f408a1d2829",
    "symbol": "TRGP",
    "name": "Targa Resources Corp.",
    "priceUsd": 264.170013
  },
  {
    "address": "0xa10ae176e801b01129a73d23e3e22cfddf452bd1",
    "symbol": "TGT",
    "name": "Target Corporation",
    "priceUsd": 126.610001
  },
  {
    "address": "0x5f2f870023187e7fa32684f60bd08b111c5fb30c",
    "symbol": "ALL",
    "name": "The Allstate Corporation",
    "priceUsd": 217.179993
  },
  {
    "address": "0xf0fb20a5ddc92194169833334f97e9bf5c05ecfc",
    "symbol": "OKE",
    "name": "ONEOK, Inc.",
    "priceUsd": 87.790001
  },
  {
    "address": "0xf94644997c9affbeb377673d31db29c00ed0b61e",
    "symbol": "NUE",
    "name": "Nucor Corporation",
    "priceUsd": 254.320007
  },
  {
    "address": "0x158dd4f6a377b575b097086dfd5d646171291983",
    "symbol": "F",
    "name": "Ford Motor Company",
    "priceUsd": 14.95
  },
  {
    "address": "0x5b72f53c197c00c50a2718534635140b5429eb45",
    "symbol": "OXY",
    "name": "Occidental Petroleum Corporation",
    "priceUsd": 56.549999
  },
  {
    "address": "0x4ac2d55a345c8feac99414974e7a0859465f7db9",
    "symbol": "ALAB",
    "name": "Astera Labs, Inc.",
    "priceUsd": 341.700012
  },
  {
    "address": "0xe2e2bda32147a9be06786e47a40e2b0b8640d723",
    "symbol": "AJG",
    "name": "Arthur J. Gallagher & Co.",
    "priceUsd": 217.050003
  },
  {
    "address": "0x6bbea5aeae576dc7b0eeac66fc887855deb07790",
    "symbol": "NU",
    "name": "Nu Holdings Ltd.",
    "priceUsd": 11.88
  },
  {
    "address": "0xca1420cb4c7ed70db33883f854952ad99598ec1f",
    "symbol": "CARR",
    "name": "Carrier Global Corporation",
    "priceUsd": 71.239998
  },
  {
    "address": "0x68172c2b290bba7d14ebd8e3764466974a1aa111",
    "symbol": "LHX",
    "name": "L3Harris Technologies, Inc.",
    "priceUsd": 308.170013
  },
  {
    "address": "0x3385949ff3ac14aaa69a64ff0e3c06997ea07230",
    "symbol": "MET",
    "name": "MetLife, Inc.",
    "priceUsd": 85.57
  },
  {
    "address": "0x5405ecf7bd4d50318e7a2693f2ef86a799905526",
    "symbol": "KEYS",
    "name": "Keysight Technologies, Inc.",
    "priceUsd": 331.429993
  },
  {
    "address": "0xef863094b7db3a56fd75974fb391d590c3fb5022",
    "symbol": "FANG",
    "name": "Diamondback Energy, Inc.",
    "priceUsd": 194.240005
  },
  {
    "address": "0x5b686b00034a443e07772ceafcd95a30e71338dc",
    "symbol": "COR",
    "name": "Cencora, Inc.",
    "priceUsd": 279.570007
  },
  {
    "address": "0x49ecc0ea88d67043466195819625984504d1215f",
    "symbol": "TER",
    "name": "Teradyne, Inc.",
    "priceUsd": 369.209991
  },
  {
    "address": "0x27abf8f843739f5e4b1816eeca01c569f042fc87",
    "symbol": "DVN",
    "name": "Devon Energy Corporation",
    "priceUsd": 44.07
  },
  {
    "address": "0x8265a50aaa87ce049c64167eca8cf9ea6b52ce42",
    "symbol": "NBIS",
    "name": "Nebius Group N.V.",
    "priceUsd": 220.119995
  },
  {
    "address": "0x78ac2a931eebe6a0e66cc6053a664888913449f1",
    "symbol": "CVE",
    "name": "Cenovus Energy Inc.",
    "priceUsd": 27.65
  },
  {
    "address": "0x133c403148c777b6318e48b065cb0b5b9e867280",
    "symbol": "FAST",
    "name": "Fastenal Company",
    "priceUsd": 46.580002
  },
  {
    "address": "0xa2b241c5a8311c43b33c6a48ee3f78397ab7ebe4",
    "symbol": "CRWV",
    "name": "CoreWeave, Inc.",
    "priceUsd": 98.449997
  },
  {
    "address": "0x802f3ec0cf5cc0552455db7c95f9e3c0b4c98315",
    "symbol": "EA",
    "name": "Electronic Arts Inc.",
    "priceUsd": 202.479996
  },
  {
    "address": "0xdce65cc302a350ff7571402dfea99829a91e631a",
    "symbol": "AZO",
    "name": "AutoZone, Inc.",
    "priceUsd": 3137.75
  },
  {
    "address": "0xc7df53194a64c69d309e8adb79ea7e3b5b2d6292",
    "symbol": "AME",
    "name": "AMETEK, Inc.",
    "priceUsd": 229.800003
  },
  {
    "address": "0x78758080fe46abc5feada788191ecb404a894794",
    "symbol": "LNG",
    "name": "Cheniere Energy, Inc.",
    "priceUsd": 239.399994
  },
  {
    "address": "0x884b3b5c7b1c906e58217a3f7cec575f17ec6610",
    "symbol": "CAH",
    "name": "Cardinal Health, Inc.",
    "priceUsd": 212.669998
  },
  {
    "address": "0xb8ddc2d52173eede14c2fa832bedee3dd42dc16a",
    "symbol": "ETR",
    "name": "Entergy Corporation",
    "priceUsd": 109.660004
  },
  {
    "address": "0x72c035fc72a5777b6b36e8c7d815516394b9ffad",
    "symbol": "DAL",
    "name": "Delta Air Lines, Inc.",
    "priceUsd": 81.169998
  },
  {
    "address": "0x4042215bfcfb1df6e64c12f3494c470594454137",
    "symbol": "CTVA",
    "name": "Corteva, Inc.",
    "priceUsd": 75.010002
  },
  {
    "address": "0xf271ccb6b144f60876f96981a7eedaa603e0cd54",
    "symbol": "EW",
    "name": "Edwards Lifesciences Corporation",
    "priceUsd": 87.540001
  },
  {
    "address": "0xef00ba0c3dd1be90a5b2e89e0225c58481aaadb6",
    "symbol": "ODFL",
    "name": "Old Dominion Freight Line, Inc.",
    "priceUsd": 248.729996
  },
  {
    "address": "0xe159d21fa81e8bbabf9a417482a01a2814ae35a3",
    "symbol": "NDAQ",
    "name": "Nasdaq, Inc.",
    "priceUsd": 87.519997
  },
  {
    "address": "0xbb1e17b166b86a773a30595c1350c8406601e5e6",
    "symbol": "ROK",
    "name": "Rockwell Automation, Inc.",
    "priceUsd": 460.470001
  },
  {
    "address": "0xd232df2032620392e61adf589498cc5e113c8d96",
    "symbol": "WPM",
    "name": "Wheaton Precious Metals Corp.",
    "priceUsd": 112.580002
  },
  {
    "address": "0x2e3df1c9f42dca41b88de3980755cc0b8ccbb668",
    "symbol": "XEL",
    "name": "Xcel Energy Inc.",
    "priceUsd": 77.870003
  },
  {
    "address": "0xc29cc48364c70cb36e64078448c99f2f6ae89f7e",
    "symbol": "FITB",
    "name": "Fifth Third Bancorp",
    "priceUsd": 52.709999
  },
  {
    "address": "0x124991f75043ef6d26d0617683565effa42b795b",
    "symbol": "MCHP",
    "name": "Microchip Technology Incorporated",
    "priceUsd": 91.470001
  },
  {
    "address": "0x75009fc8bd33abc0cd0cc7a6497999b8d85b8121",
    "symbol": "EBAY",
    "name": "eBay Inc.",
    "priceUsd": 108.660004
  },
  {
    "address": "0x9945e10f837819e7b21530bba359753eda44c96a",
    "symbol": "ADSK",
    "name": "Autodesk, Inc.",
    "priceUsd": 224.080002
  },
  {
    "address": "0x92a23842fb03311486df40d49a68451ebe2375e5",
    "symbol": "VST",
    "name": "Vistra Corp.",
    "priceUsd": 146.220001
  },
  {
    "address": "0xf19adac5ee7a6a333c3a8e5acaae55a8307b4df6",
    "symbol": "EXC",
    "name": "Exelon Corporation",
    "priceUsd": 45.330002
  },
  {
    "address": "0x40396f91101c3c72dc62635d82f92d5cdca63eb3",
    "symbol": "STT",
    "name": "State Street Corporation",
    "priceUsd": 163.25
  },
  {
    "address": "0xcdef928947c9178229257b135841a97809a6ce68",
    "symbol": "GRMN",
    "name": "Garmin Ltd.",
    "priceUsd": 237.850006
  },
  {
    "address": "0x5f10b2b93757c038fce16ba046e68ae9077c952b",
    "symbol": "MSCI",
    "name": "MSCI Inc.",
    "priceUsd": 607.539978
  },
  {
    "address": "0xad5a421fd4282f7409ffa302f99265404a47b20d",
    "symbol": "IDXX",
    "name": "IDEXX Laboratories, Inc.",
    "priceUsd": 578.890015
  },
  {
    "address": "0xf48322f84755c08199710054d89ce28477748129",
    "symbol": "CRDO",
    "name": "Credo Technology Group Holding Ltd",
    "priceUsd": 234.320007
  },
  {
    "address": "0x9627d22d5a977fb040d53d5db7de397b288e0374",
    "symbol": "HUM",
    "name": "Humana Inc.",
    "priceUsd": 363.179993
  },
  {
    "address": "0x30ac234039a3547e1224897df22a291f5d90bf99",
    "symbol": "KDP",
    "name": "Keurig Dr Pepper Inc.",
    "priceUsd": 31.48
  },
  {
    "address": "0x5e2d7f659399eda9d4f8084a7f9ba67ec13d1909",
    "symbol": "ON",
    "name": "ON Semiconductor Corporation",
    "priceUsd": 117
  },
  {
    "address": "0x19f915716cf0a4a360c4e59b681bc99c673ca75a",
    "symbol": "CLS",
    "name": "Celestica Inc.",
    "priceUsd": 371.859985
  },
  {
    "address": "0x4054183cb1d9b1ea3302406c0823ff80a6b95855",
    "symbol": "YUM",
    "name": "Yum! Brands, Inc.",
    "priceUsd": 151.630005
  },
  {
    "address": "0xb13994a3099182292fb29492267793153074cb6f",
    "symbol": "DHI",
    "name": "D.R. Horton, Inc.",
    "priceUsd": 151.070007
  },
  {
    "address": "0x1dd912c5a6cdd2efe1d8fe206cc8ef1fd0601a1d",
    "symbol": "CCJ",
    "name": "Cameco Corporation",
    "priceUsd": 102.269997
  },
  {
    "address": "0xb63919e013d5e05d80eb1f671462504eafe3fd93",
    "symbol": "GFS",
    "name": "GLOBALFOUNDRIES Inc.",
    "priceUsd": 75.260002
  },
  {
    "address": "0x63602ed098150d659b4ea96da763ac078682a05d",
    "symbol": "MSTR",
    "name": "Strategy Inc",
    "priceUsd": 117.019997
  },
  {
    "address": "0x55304897dd5ea81ee896fdbb4fec8b30ee2b9471",
    "symbol": "BDX",
    "name": "Becton, Dickinson and Company",
    "priceUsd": 152.039993
  },
  {
    "address": "0xd6a7fab82de4042e65df77120febfb5182d8d156",
    "symbol": "COIN",
    "name": "Coinbase Global, Inc.",
    "priceUsd": 155.5
  },
  {
    "address": "0x19d7523284386cfe10e8868ccba6affc871e4c6b",
    "symbol": "FNV",
    "name": "Franco-Nevada Corporation",
    "priceUsd": 212.160004
  },
  {
    "address": "0xf8fae2468bbeb1b22a820943571b80adacec0f6b",
    "symbol": "KR",
    "name": "The Kroger Co.",
    "priceUsd": 62.990002
  },
  {
    "address": "0xeb246b908f7705506fdce18cb6bb10fcc8baf6c8",
    "symbol": "AIG",
    "name": "American International Group, Inc.",
    "priceUsd": 73.919998
  },
  {
    "address": "0xce31df970c9bf42cdc515f64d789b57f8b0fce68",
    "symbol": "AU",
    "name": "AngloGold Ashanti plc",
    "priceUsd": 84.43
  },
  {
    "address": "0x40b0963f99eadcf6ef7336839cc68aefa7aee898",
    "symbol": "XYZ",
    "name": "Block, Inc.",
    "priceUsd": 68.290001
  },
  {
    "address": "0x7d0d4567140aef4c0763edc61e7dc0400b23f057",
    "symbol": "ED",
    "name": "Consolidated Edison, Inc.",
    "priceUsd": 106.400002
  },
  {
    "address": "0xc075f8921c2cb941b77b8a29a2b3483ff9bf87e9",
    "symbol": "VIK",
    "name": "Viking Holdings Ltd",
    "priceUsd": 90.309998
  },
  {
    "address": "0x78062337dc37bf34b76156566a682f07ade06491",
    "symbol": "CBRE",
    "name": "CBRE Group, Inc.",
    "priceUsd": 136.100006
  },
  {
    "address": "0x9e1844273c4e1802aaf9e890d73211a3081251e7",
    "symbol": "ADM",
    "name": "Archer-Daniels-Midland Company",
    "priceUsd": 80.120003
  },
  {
    "address": "0x765c5f4eb9dac4c0e84ae40c5eb616a5adb88c04",
    "symbol": "PEG",
    "name": "Public Service Enterprise Group Incorporated",
    "priceUsd": 78.589996
  },
  {
    "address": "0xa54ea24a8864e5041b347bbd8cfb866fb9fa5912",
    "symbol": "TTWO",
    "name": "Take-Two Interactive Software, Inc.",
    "priceUsd": 212.050003
  },
  {
    "address": "0xe14484c11c13d2e76442a3eb158c8928b148c046",
    "symbol": "CMG",
    "name": "Chipotle Mexican Grill, Inc.",
    "priceUsd": 29.879999
  },
  {
    "address": "0xd2b8716dab3cc1b9796b28a26fb90360d69e8c00",
    "symbol": "LYV",
    "name": "Live Nation Entertainment, Inc.",
    "priceUsd": 162.660004
  },
  {
    "address": "0x9df24127fe41fea928fbb4363b7d27f939127bed",
    "symbol": "ALNY",
    "name": "Alnylam Pharmaceuticals, Inc.",
    "priceUsd": 297.690002
  },
  {
    "address": "0x9f01cb30a99ee1c8a7404117ec2acb37adcaa1cc",
    "symbol": "STLD",
    "name": "Steel Dynamics, Inc.",
    "priceUsd": 269.799988
  },
  {
    "address": "0x65101ee8db768c838ca3c94a7b8173335ffc6b1a",
    "symbol": "ESLT",
    "name": "Elbit Systems Ltd.",
    "priceUsd": 837.590027
  },
  {
    "address": "0xcd37ba4098e73fba403a19cc6b3c0d217b3cc9cc",
    "symbol": "SYY",
    "name": "Sysco Corporation",
    "priceUsd": 77.550003
  },
  {
    "address": "0x39c72e6b74981667877dd8521a1aaf949259805b",
    "symbol": "JBL",
    "name": "Jabil Inc.",
    "priceUsd": 362.380005
  },
  {
    "address": "0x6f563e47809a7b057df6b135cd34d258bccdb667",
    "symbol": "A",
    "name": "Agilent Technologies, Inc.",
    "priceUsd": 135.479996
  },
  {
    "address": "0xccb6c7872f6f9943a2ac43d134954a29e65a8621",
    "symbol": "WEC",
    "name": "WEC Energy Group, Inc.",
    "priceUsd": 113.099998
  },
  {
    "address": "0xb45b6985a481e25800f7128d9f1bf33e019eea44",
    "symbol": "PCG",
    "name": "PG&E Corporation",
    "priceUsd": 16.58
  },
  {
    "address": "0x5e6a91edb10412e123ce37b020abf8d26bb1b3d1",
    "symbol": "PRU",
    "name": "Prudential Financial, Inc.",
    "priceUsd": 103.699997
  },
  {
    "address": "0x26ffec9da6c52995d9a263439525e20404637274",
    "symbol": "PAYX",
    "name": "Paychex, Inc.",
    "priceUsd": 100.279999
  },
  {
    "address": "0x0ef6762c597d755e880f4d5fb778f8ed99060c38",
    "symbol": "AXON",
    "name": "Axon Enterprise, Inc.",
    "priceUsd": 452.51001
  },
  {
    "address": "0xd9d52b88534e79ff731d70f0f0ee4098902f590d",
    "symbol": "CCL",
    "name": "Carnival Corporation Ltd.",
    "priceUsd": 27.73
  },
  {
    "address": "0xb3e028d23d9fd523b67b148c95a9f4f23f64d24e",
    "symbol": "PYPL",
    "name": "PayPal Holdings, Inc.",
    "priceUsd": 41.459999
  },
  {
    "address": "0x93520114c8373ba780108ed314686256595f6dd1",
    "symbol": "HSY",
    "name": "The Hershey Company",
    "priceUsd": 175.839996
  },
  {
    "address": "0x763e1891b767ece29e377d68f6021d251a0f25f2",
    "symbol": "WAT",
    "name": "Waters Corporation",
    "priceUsd": 371.149994
  },
  {
    "address": "0x5e0df751a0694ce2338f82f5d1c8a8290702529a",
    "symbol": "RKT",
    "name": "Rocket Companies, Inc.",
    "priceUsd": 13.18
  },
  {
    "address": "0x5b7b9e307f5a94575406c289cba0d7032702f498",
    "symbol": "HIG",
    "name": "The Hartford Insurance Group, Inc.",
    "priceUsd": 128.970001
  },
  {
    "address": "0x96ca63ea239e55ee927aae68325e9360fea1f33e",
    "symbol": "VMC",
    "name": "Vulcan Materials Company",
    "priceUsd": 279
  },
  {
    "address": "0x5519f8f64c278b707d07064f5e8e42a7c591e6ea",
    "symbol": "KVUE",
    "name": "Kenvue Inc.",
    "priceUsd": 17.92
  },
  {
    "address": "0x7e7b67068465ebb616e9ba156233f009c353ee5d",
    "symbol": "EME",
    "name": "EMCOR Group, Inc.",
    "priceUsd": 827.780029
  },
  {
    "address": "0x8b123ca38e9cd5200a3a194125a997e64198ea8e",
    "symbol": "HBAN",
    "name": "Huntington Bancshares Incorporated",
    "priceUsd": 16.82
  },
  {
    "address": "0xb76d2a5a616b5aa7514765a08c0623044fff334c",
    "symbol": "ZTS",
    "name": "Zoetis Inc.",
    "priceUsd": 82.199997
  },
  {
    "address": "0xabe133ecb9e808d0e48936bf35addcb06a3a7451",
    "symbol": "WDAY",
    "name": "Workday, Inc.",
    "priceUsd": 140.229996
  },
  {
    "address": "0x54a3093f5e4415f77e52f40b0faa5f3e5d39a128",
    "symbol": "CASY",
    "name": "Casey's General Stores, Inc.",
    "priceUsd": 761.179993
  },
  {
    "address": "0x89ec78b779e00bc99044656b04a8db059c9b7270",
    "symbol": "MSTRx",
    "name": "Strategy Inc",
    "priceUsd": 117.019997
  },
  {
    "address": "0xb1eb0688fea9011f38275a77b1be7f2dcfb290c3",
    "symbol": "TSLAx",
    "name": "Tesla, Inc.",
    "priceUsd": 396.679993
  },
  {
    "address": "0x1d2dc78a673e3040e188b2551da2ec4785fb49a1",
    "symbol": "NVDAx",
    "name": "NVIDIA Corporation",
    "priceUsd": 208.190002
  }
];
