// AUTO-EXPORT: reads Hardhat artifacts from artifacts/ and emits typed ABIs into abis.ts.
// Run after `npx hardhat compile`:  node scripts/export-abi.mjs
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";

const ARTIFACTS = "artifacts";
const TARGET = "abis.ts";

// Public modules exposed to TS consumers. `sol` is the source path under contracts/;
// Hardhat writes each artifact to artifacts/<sol>/<Name>.json.
const EXPOSE = [
  // L1 — factory + vault implementations
  { name: "CloneFactory", sol: "contracts/L1/CloneFactory.sol" },
  { name: "BasketVault", sol: "contracts/L1/BasketVault.sol" },
  { name: "ManagedVault", sol: "contracts/L1/ManagedVault.sol" },
  { name: "CommittedVault", sol: "contracts/L1/CommittedVault.sol" },
  // L2 — read-price stack
  { name: "OracleRouter", sol: "contracts/L2/OracleRouter.sol" },
  { name: "NAVEngine", sol: "contracts/L2/NAVEngine.sol" },
  // L4 — fair-value layer
  { name: "PriceAggregator", sol: "contracts/L4/PriceAggregator.sol" },
  { name: "FairValueNAV", sol: "contracts/L4/FairValueNAV.sol" },
  // L3 — rebalance + keeper-incentive
  { name: "ManagedRebalanceVault", sol: "contracts/L3/ManagedRebalanceVault.sol" },
  { name: "KeeperModule", sol: "contracts/L3/KeeperModule.sol" },
  { name: "RebalanceAuction", sol: "contracts/L3/RebalanceAuction.sol" },
  { name: "RebalanceObserver", sol: "contracts/L3/RebalanceObserver.sol" },
  { name: "RebalanceModule", sol: "contracts/L3/RebalanceModule.sol" },
];

let body = "// AUTO-GENERATED by scripts/export-abi.mjs — do not edit by hand.\n\n";
for (const { name, sol } of EXPOSE) {
  const artifact = JSON.parse(readFileSync(join(ARTIFACTS, sol, `${name}.json`), "utf8"));
  body += `export const ${name}Abi = ${JSON.stringify(artifact.abi)} as const;\n\n`;
}
mkdirSync(dirname(TARGET), { recursive: true });
writeFileSync(TARGET, body);
console.log(`Wrote ${EXPOSE.length} ABIs to ${TARGET}`);
