// AUTO-EXPORT: reads Hardhat artifacts from artifacts/ and emits typed ABIs into abis.ts.
// Run after `npx hardhat compile`:  node scripts/export-abi.mjs
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";

const ARTIFACTS = "artifacts";
const TARGET = "abis.ts";

// Public modules exposed to TS consumers. `sol` is the source path under contracts/;
// Hardhat writes each artifact to artifacts/<sol>/<Name>.json.
const EXPOSE = [
  { name: "BasketVault", sol: "contracts/L1/BasketVault.sol" },
  { name: "BasketFactory", sol: "contracts/L1/BasketFactory.sol" },
  { name: "ManagedVault", sol: "contracts/L1/ManagedVault.sol" },
];

let body = "// AUTO-GENERATED by scripts/export-abi.mjs — do not edit by hand.\n\n";
for (const { name, sol } of EXPOSE) {
  const artifact = JSON.parse(readFileSync(join(ARTIFACTS, sol, `${name}.json`), "utf8"));
  body += `export const ${name}Abi = ${JSON.stringify(artifact.abi)} as const;\n\n`;
}
mkdirSync(dirname(TARGET), { recursive: true });
writeFileSync(TARGET, body);
console.log(`Wrote ${EXPOSE.length} ABIs to ${TARGET}`);
